version: '3'
services:
  validator0:
    container_name: validator0
    image: sshd:latest
    ports:
      - "2201:22"
      - "26657:26657"
      - "9090:9090"
    networks:
      testnet:
        ipv4_address: 10.10.1.1
  validator1:
    container_name: validator1
    image: sshd:latest
    ports:
      - "2202:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.2
  validator2:
    container_name: validator2
    image: sshd:latest
    ports:
      - "2203:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.3
  validator3:
    container_name: validator3
    image: sshd:latest
    ports:
      - "2204:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.4

networks:
  testnet:
    external:
      name: thetanet

# networks:
#   testnet:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.10.0/16
