version: '3'
services:
  relayer:
    container_name: relayer1
    image: sshd:latest
    ports:
      - "2210:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.9
    cap_add:
      - NET_ADMIN

networks:
  testnet:
    external:
      name: thetanet

# networks:
#   testnet:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.10.0/16
