version: '3'
services:
  validator5:
    container_name: validator4
    image: sshd:latest
    ports:
      - "2205:22"
      - "26658:26657"
      - "9091:9090"
    networks:
      testnet:
        ipv4_address: 10.10.1.5
  validator6:
    container_name: validator5
    image: sshd:latest
    ports:
      - "2206:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.6
  validator7:
    container_name: validator6
    image: sshd:latest
    ports:
      - "2207:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.7
  validator8:
    container_name: validator7
    image: sshd:latest
    ports:
      - "2208:22"
    networks:
      testnet:
        ipv4_address: 10.10.1.8

networks:
  testnet:
    external:
      name: thetanet

# networks:
#   testnet:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 192.168.10.0/16
